/**
 * german-art-schools-api — read-only REST API over the generated data
 * snapshot in api/data/, deployed as a Cloudflare Worker.
 *
 * Versioning stance: /v1 is ADDITIVE-ONLY. New fields and new endpoints may
 * be added under /v1; removing/renaming/retyping anything requires /v2.
 *
 * Extension points (do NOT edit this file to implement them):
 * - /v1/search → src/routes/search.ts (owned by the semantic search agent)
 * - /mcp      → src/mcp/            (owned by the MCP agent)
 * Both are already mounted with appropriate CORS below.
 */
import { cors } from 'hono/cors';
import { createRouter, errorBody } from './router';
import { cacheMiddleware } from './middleware/cache';
import { meta } from './data';
import metaRoutes from './routes/meta';
import schoolsRoutes from './routes/schools';
import programsRoutes from './routes/programs';
import graphRoutes from './routes/graph';
import searchRoutes from './routes/search';
import mcpApp from './mcp';

const app = createRouter();

// ---------- cross-cutting ----------

app.onError((err, c) => {
  console.error(err);
  return c.json(errorBody('internal_error', 'internal server error'), 500);
});
app.notFound((c) => c.json(errorBody('not_found', 'no such route'), 404));

// /v1 is read-only: GET-only CORS. /mcp needs POST (and DELETE for session
// teardown per the MCP streamable-HTTP transport), so it gets its own policy.
app.use('/v1/*', cors({ origin: '*', allowMethods: ['GET', 'HEAD', 'OPTIONS'] }));
app.use('/mcp/*', cors({ origin: '*', allowMethods: ['GET', 'POST', 'DELETE', 'OPTIONS'] }));
app.use('/mcp', cors({ origin: '*', allowMethods: ['GET', 'POST', 'DELETE', 'OPTIONS'] }));

// ETag (from data_hash + path + query) + Cache-Control on every /v1 response.
app.use('/v1/*', cacheMiddleware);

// ---------- /v1 ----------

app.route('/v1', metaRoutes);
app.route('/v1', schoolsRoutes);
app.route('/v1', programsRoutes);
app.route('/v1', graphRoutes);
app.route('/v1/search', searchRoutes);
app.route('/mcp', mcpApp);

// ---------- docs ----------

app.doc('/openapi.json', {
  openapi: '3.0.0',
  info: {
    title: 'German Art Schools API',
    version: '1.0.0',
    description:
      'Read-only API over a snapshot of German art school and program data. ' +
      '/v1 is additive-only: fields are never removed or retyped.',
  },
  servers: [{ url: '/' }],
});

app.get('/', (c) =>
  c.html(`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>German Art Schools API</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 46rem; margin: 3rem auto; padding: 0 1rem; line-height: 1.6; color: #222; }
    code { background: #f4f4f4; padding: .1em .35em; border-radius: 4px; }
    li { margin: .25rem 0; }
  </style>
</head>
<body>
  <h1>German Art Schools API</h1>
  <p>Read-only REST API over a snapshot of German art school and program data.</p>
  <p>Data snapshot: <code>${meta.snapshot_date}</code> &middot; ${meta.counts.schools} schools &middot; ${meta.counts.programs} programs</p>
  <p>OpenAPI spec: <a href="/openapi.json">/openapi.json</a></p>
  <h2>Endpoints</h2>
  <ul>
    <li><code>GET /v1/meta</code> — snapshot metadata</li>
    <li><code>GET /v1/schools</code> — list schools (<code>state</code>, <code>city</code>, <code>type</code>)</li>
    <li><code>GET /v1/schools/{id}</code> — one school</li>
    <li><code>GET /v1/programs</code> — list programs (<code>degree_level</code>, <code>language</code>, <code>school</code>, <code>portfolio_required</code>, <code>state</code>, <code>q</code>, <code>open_on</code>, <code>limit</code>, <code>offset</code>)</li>
    <li><code>GET /v1/programs/{id}</code> — one program</li>
    <li><code>GET /v1/programs/{id}/similar</code> — similar programs (<code>limit</code>, <code>min_weight</code>)</li>
    <li><code>GET /v1/graph</code> — full similarity graph</li>
    <li><code>GET /v1/search</code> — semantic search over program embeddings (<code>q</code>, <code>degree_level</code>, <code>language</code>, <code>min_score</code>, <code>limit</code>)</li>
    <li><code>POST /mcp</code> — MCP server (streamable HTTP, stateless); tools: <code>search_programs</code>, <code>list_open_deadlines</code>, <code>list_schools</code>, <code>get_school</code>, <code>get_program</code>, <code>find_similar_programs</code></li>
  </ul>
  <p><code>/v1</code> is additive-only and cacheable (<code>ETag</code> + <code>Cache-Control: public, max-age=3600</code>).</p>
</body>
</html>`),
);

export default app;
